apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  environment: prod

# 1. Override the dev secrets with production secrets!
secretGenerator:
  - name: craftcloud-secrets
    behavior: replace # This tells Kustomize to overwrite the base secret
    envs:
      - prod-secrets.env # Create this file to hold your real DB passwords

# 2. Apply production-specific patches
patches:
  - path: patch-resources.yaml