apiVersion: v1
kind: Service
metadata:
  name: valheim-service
spec:
  type: LoadBalancer 
  selector:
    app: valheim-server # This matches the label in your deployment.yaml
  ports:
    - name: game-port
      port: 2456
      targetPort: 2456
      protocol: UDP
    - name: query-port
      port: 2457
      targetPort: 2457
      protocol: UDP