apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-gateway
  labels:
    app: craftcloud
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  # This references the TLS certs you will store in config/secret.yaml
  tls:
    - hosts:
        - "localhost" # Replace with your actual domain when moving to prod
      secretName: gateway-certs 
  rules:
    - host: "localhost" # Replace with your actual domain
      http:
        paths:
          - path: /api/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: manager-api
                port:
                  number: 5000
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: dashboard
                port:
                  number: 80