apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Inherit everything from the base folder
resources:
  - ../../base

# 2. Automatically apply a label to EVERYTHING in this environment
commonLabels:
  environment: dev